// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA2w38Cf6dUoTYQRWA4N6_hyNDmMGk-oI',
    appId: '1:739972871938:web:04f90ee2aa593d6122b41b',
    messagingSenderId: '739972871938',
    projectId: 'e-commerce-adv',
    authDomain: 'e-commerce-adv.firebaseapp.com',
    storageBucket: 'e-commerce-adv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWRptO-0bxqhqipUXuwadBq4nypcHt4Ts',
    appId: '1:739972871938:android:81f8021cfb1a48a222b41b',
    messagingSenderId: '739972871938',
    projectId: 'e-commerce-adv',
    storageBucket: 'e-commerce-adv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuv6yK7yPeYTvyWvyxJJXmwA2V5HTBB4Q',
    appId: '1:739972871938:ios:eb377b62d7fed4a622b41b',
    messagingSenderId: '739972871938',
    projectId: 'e-commerce-adv',
    storageBucket: 'e-commerce-adv.appspot.com',
    iosBundleId: 'com.thomas.meshail.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuv6yK7yPeYTvyWvyxJJXmwA2V5HTBB4Q',
    appId: '1:739972871938:ios:e1ea5eb0a49ea7dd22b41b',
    messagingSenderId: '739972871938',
    projectId: 'e-commerce-adv',
    storageBucket: 'e-commerce-adv.appspot.com',
    iosBundleId: 'com.thomas.meshail.eCommerce.RunnerTests',
  );
}
